import Login from "./pages/Authentication/login";
import AdminLogin from "./pages/Authentication/adminLogin";
import Signup from "./pages/Authentication/signup";
import Navbar from "./components/navbar";
import EditProfile from "./pages/editProfile";
import Home from "./pages/home";
import Product from "./pages/Shop/product";
import ShoppingCart from "./pages/Cart/shoppingCartMain";
import Header from "./components/header";
import Footer from "./components/footer";
import Mobilenav from "./components/mobilenav";
import CartBilling from "./pages/Cart/cartbilling";
import Shop from "./pages/Shop/shop";
import { useState, useEffect } from "react";
import OrderPlaced from "./pages/Cart/orderplaced";
import Error from "./pages/error";

import { Routes, Route, BrowserRouter } from "react-router-dom";

function App() {
  const [products, setProducts] = useState([]);

  function fetchProducts() {
    fetch("http://localhost:5000/products")
      .then((response) => response.json())
      .then((json) => setProducts(json));
  }

  useEffect(() => {
    fetchProducts();
  }, []);

  return (
    <div>
      <BrowserRouter>
        <Routes>
          <Route path="/login" element={<Login />} />
          <Route path="/signup" element={<Signup />} />
          <Route path="/home" element={<Home />} />
          {/* Using conditional component rendering to avoid empty array generated by useEffect */}
          {products.length > 0 && (
            <Route path="/product/:name" element={<Product products={products}/>}/>
          )}
         {products.length > 0 &&<Route path="/shop" element={<Shop products={products} />} />}
          <Route path="/adminlogin" element={<AdminLogin />} />
          <Route path="/cart" element={<ShoppingCart/>}></Route>
          <Route path="/billing" element={<CartBilling />} />
          <Route path="/home" element={<Home/>}></Route>
          <Route path="/orderplaced" element={<OrderPlaced/>}></Route>
          <Route path="*" element={<Error/>}></Route>
        </Routes>

       
      </BrowserRouter>
      
    </div>
  );
}

export default App;
