import Login from "./pages/login";
import Signup from './pages/signup'
import Navbar from "./components/navbar";
import EditProfile from "./pages/editProfile";
import Home from "./pages/home";
import Product from "./pages/product";
import ShoppingCart from "./pages/shoppingCart";
import Header from "./components/header";
import Footer from "./components/footer";
import Mobilenav from "./components/mobilenav";
import Shop from "./pages/shop";
import {useState,useEffect} from 'react'

import { Routes,Route, BrowserRouter  } from "react-router-dom";

function App() {
  const [products, setProducts] = useState([]);
  const [cartItems,setCartItems]= useState([])

  function fetchProducts(){
    fetch("http://localhost:5000/products")
  .then((response) => response.json())
  .then((json) =>  setProducts(json));
}

function fetchCartItems(){
  fetch("http://localhost:5000/cart")
  .then((response) => response.json())
  .then((json) =>  setCartItems(json));
}

useEffect( () => {
   fetchProducts();
   fetchCartItems();
}, []);

  return (
    <div>
      <BrowserRouter>
      <Header/>
      <Navbar/>

      <Routes>
        <Route path="/login" element={<Login />}/>
        <Route path="/signup" element={<Signup />}/>
        <Route path="/home" element={<Home />}/>
        {/* Using conditional component rendering to avoid empty array generated by useEffect */}
        {products.length>0 &&<Route path="/product/:name" element={<Product products={products}/>}/>}
        <Route path="/shop" element={<Shop />}/>
        {cartItems.length>0 &&<Route path="/cart" element={<ShoppingCart cartItems={cartItems} />}></Route>}
        <Route path="*" element={<Home />}></Route>
        
      </Routes>
    
      <Mobilenav/>
      <Footer/>
      </BrowserRouter>
    </div>
  );
}

export default App;
