import Login from "./pages/Authentication/login";
import Signup from "./pages/Authentication/signup";
import Navbar from "./components/navbar";
import EditProfile from "./pages/editProfile";
import Home from "./pages/home";
import Product from "./pages/Shop/product";
import ShoppingCart from "./pages/Cart/shoppingCartMain";
import Header from "./components/header";
import Footer from "./components/footer";
import Mobilenav from "./components/mobilenav";
import CartBilling from "./pages/Cart/cartbilling";
import Shop from "./pages/Shop/shop";
import { useState, useEffect } from "react";

import { Routes, Route, BrowserRouter } from "react-router-dom";

function App() {
  const [products, setProducts] = useState([]);

  function fetchProducts() {
    fetch("http://localhost:5000/products")
      .then((response) => response.json())
      .then((json) => setProducts(json));
  }

  useEffect(() => {
    fetchProducts();
  }, []);

  return (
    <div>
      <BrowserRouter>
        <Header />
        <Navbar />

        <Routes>
          <Route path="/login" element={<Login />} />
          <Route path="/signup" element={<Signup />} />
          <Route path="/home" element={<Home />} />
          {/* Using conditional component rendering to avoid empty array generated by useEffect */}
          {products.length > 0 && (
            <Route path="/product/:name" element={<Product products={products}/>}/>
          )}
          <Route path="/shop" element={<Shop />} />
          <Route path="/cart" element={<ShoppingCart/>}></Route>
          <Route path="/billing" element={<CartBilling />} />
          <Route path="*" element={<Home />}></Route>
        </Routes>

        <Mobilenav />
        <Footer />
      </BrowserRouter>
    </div>
  );
}

export default App;
